In [24]:
import numpy as np
import pandas as pd

In [25]:
np.set_printoptions(suppress=True)

In [26]:
np.set_printoptions(suppress=True)

In [83]:
data = pd.read_excel(r"C:\Users\Sivakumar\Desktop\GCN_stock_price_prediction-main\tech_sorted.xlsx",index_col=0)
data

4THGEN.BO  4THGEN.BO.1  4THGEN.BO.2  4THGEN.BO.3  4THGEN.BO.4  \
DATE                                                                        
2010-01-04       25.0         25.0         25.0         25.0          0.0   
2010-01-05       25.0         25.0         25.0         25.0          0.0   
2010-01-06       25.0         25.0         25.0         25.0          0.0   
2010-01-07       25.0         25.0         25.0         25.0          0.0   
2010-01-08       25.0         25.0         25.0         25.0          0.0   
...               ...          ...          ...          ...          ...   
2020-12-23        4.0          4.0          4.0          4.0          0.0   
2020-12-24        4.0          4.0          4.0          4.0          0.0   
2020-12-28        4.0          4.0          4.0          4.0          0.0   
2020-12-29        4.0          4.0          4.0          4.0          0.0   
2020-12-30        4.0          4.0          4.0          4.0          0.0   

            ACIIN.BO  ACIIN.BO.1  ACIIN.BO.2  ACIIN.BO.3  ACIIN.BO.4  ...  \
DATE                                                                  ...   
2010-01-04     1.472       1.472       1.400       1.400     22480.0  ...   
2010-01-05     1.545       1.545       1.545       1.545     16760.0  ...   
2010-01-06     1.622       1.622       1.545       1.545     38510.0  ...   
2010-01-07     1.703       1.703       1.703       1.703     38390.0  ...   
2010-01-08     1.767       1.788       1.618       1.788     80490.0  ...   
...              ...         ...         ...         ...         ...  ...   
2020-12-23     0.400       0.400       0.400       0.400       354.0  ...   
2020-12-24     0.410       0.410       0.410       0.410      2150.0  ...   
2020-12-28     0.400       0.400       0.400       0.400      3101.0  ...   
2020-12-29     0.420       0.420       0.420       0.420      1100.0  ...   
2020-12-30     0.420       0.420       0.420       0.420         0.0  ...   

              AJEL.BO  AJEL.BO.1  AJEL.BO.2  AJEL.BO.3  AJEL.BO.4  \
DATE                                                                
2010-01-04  34.650002  36.450001  30.200001  30.500000      16288   
2010-01-05  36.799999  38.599998  33.000000  35.049999      22900   
2010-01-06  41.450001  42.900002  34.049999  37.500000      27946   
2010-01-07  40.099998  43.000000  39.099998  43.000000      12725   
2010-01-08  41.099998  45.000000  39.299999  45.000000      18240   
...               ...        ...        ...        ...        ...   
2020-12-23   2.450000   2.450000   2.450000   2.450000       1220   
2020-12-24   2.450000   2.450000   2.450000   2.450000          0   
2020-12-28   2.690000   2.690000   2.650000   2.650000       1969   
2020-12-29   2.820000   2.820000   2.820000   2.820000        211   
2020-12-30   2.960000   2.960000   2.960000   2.960000        632   

            AKSHOPTFBR.BO  AKSHOPTFBR.BO.1  AKSHOPTFBR.BO.2  AKSHOPTFBR.BO.3  \
DATE                                                                           
2010-01-04      19.400000        21.150000        19.200001        20.799999   
2010-01-05      19.400000        20.000000        19.100000        19.799999   
2010-01-06      20.049999        20.200001        19.549999        19.799999   
2010-01-07      20.250000        20.549999        19.750000        19.750000   
2010-01-08      21.600000        21.850000        20.100000        21.000000   
...                   ...              ...              ...              ...   
2020-12-23       7.350000         7.390000         6.800000         7.250000   
2020-12-24       7.810000         8.080000         7.300000         8.000000   
2020-12-28       7.800000         7.940000         7.540000         7.920000   
2020-12-29       7.820000         8.000000         7.300000         7.300000   
2020-12-30       7.730000         7.900000         7.350000         7.900000   

            AKSHOPTFBR.BO.4  
DATE                         
2010-01-0

In [84]:
#数据的列名
data.columns

Index(['4THGEN.BO', '4THGEN.BO.1', '4THGEN.BO.2', '4THGEN.BO.3', '4THGEN.BO.4',
       'ACIIN.BO', 'ACIIN.BO.1', 'ACIIN.BO.2', 'ACIIN.BO.3', 'ACIIN.BO.4',
       'AISHWARYA.BO', 'AISHWARYA.BO.1', 'AISHWARYA.BO.2', 'AISHWARYA.BO.3',
       'AISHWARYA.BO.4', 'AJEL.BO', 'AJEL.BO.1', 'AJEL.BO.2', 'AJEL.BO.3',
       'AJEL.BO.4', 'AKSHOPTFBR.BO', 'AKSHOPTFBR.BO.1', 'AKSHOPTFBR.BO.2',
       'AKSHOPTFBR.BO.3', 'AKSHOPTFBR.BO.4'],
      dtype='object')

In [85]:
#列名的截取
cut_stock_name=[]
for i in range(len(data.columns)):
    cut_stock_name.append(data.columns[i][:9])
print(cut_stock_name)
#41 stocks

['4THGEN.BO', '4THGEN.BO', '4THGEN.BO', '4THGEN.BO', '4THGEN.BO', 'ACIIN.BO', 'ACIIN.BO.', 'ACIIN.BO.', 'ACIIN.BO.', 'ACIIN.BO.', 'AISHWARYA', 'AISHWARYA', 'AISHWARYA', 'AISHWARYA', 'AISHWARYA', 'AJEL.BO', 'AJEL.BO.1', 'AJEL.BO.2', 'AJEL.BO.3', 'AJEL.BO.4', 'AKSHOPTFB', 'AKSHOPTFB', 'AKSHOPTFB', 'AKSHOPTFB', 'AKSHOPTFB']


In [88]:
#独立的股票代号
set_cut_stock_name = set(cut_stock_name)
n = 5

In [89]:
#构建input矩阵
stock_matrix = np.zeros((len(data),n,6))
stock_matrix

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       ...,

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 

In [90]:
#矩阵shape
stock_matrix.shape

(2712, 5, 6)

In [91]:
set_cut_stock_name1 =['4THGEN.BO','ACIIN.BO','AISHWARYA.BO','AJEL.BO','AKSHOPTFBR.BO','AKSHOPTFBR.NS']

set_cut_stock_name1 = set(set_cut_stock_name1)
set_cut_stock_name = sorted(set_cut_stock_name1)


In [92]:
print(set_cut_stock_name)

['4THGEN.BO', 'ACIIN.BO', 'AISHWARYA.BO', 'AJEL.BO', 'AKSHOPTFBR.BO', 'AKSHOPTFBR.NS']


In [93]:
for i in range(len(data)):
    print(i/len(data))
    for j in range(5):
        flag=0
        for k in range(data.shape[1]):
            if set_cut_stock_name[j] in data.columns[k]:
                stock_matrix[i,j,flag] = data.iloc[i,k]
                flag+=1
stock_matrix

0.0
0.0003687315634218289
0.0007374631268436578
0.0011061946902654867
0.0014749262536873156
0.0018436578171091445
0.0022123893805309734
0.0025811209439528023
0.0029498525073746312
0.00331858407079646
0.003687315634218289
0.004056047197640118
0.004424778761061947
0.004793510324483776
0.005162241887905605
0.0055309734513274336
0.0058997050147492625
0.006268436578171091
0.00663716814159292
0.007005899705014749
0.007374631268436578
0.007743362831858407
0.008112094395280236
0.008480825958702065
0.008849557522123894
0.009218289085545723
0.009587020648967551
0.00995575221238938
0.01032448377581121
0.010693215339233038
0.011061946902654867
0.011430678466076696
0.011799410029498525
0.012168141592920354
0.012536873156342183
0.012905604719764012
0.01327433628318584
0.01364306784660767
0.014011799410029498
0.014380530973451327
0.014749262536873156
0.015117994100294985
0.015486725663716814
0.015855457227138645
0.016224188790560472
0.016592920353982302
0.01696165191740413
0.01733038348082596
0.01769

array([[[    25.        ,     25.        ,     25.        ,
             25.        ,      0.        ,      0.        ],
        [     1.472     ,      1.472     ,      1.39999998,
              1.39999998,  22480.        ,      0.        ],
        [    23.35000038,     23.35000038,     21.14999962,
             21.14999962, 124154.        ,      0.        ],
        [    34.65000153,     36.45000076,     30.20000076,
             30.5       ,  16288.        ,      0.        ],
        [    19.39999962,     21.14999962,     19.20000076,
             20.79999924, 381921.        ,      0.        ]],

       [[    25.        ,     25.        ,     25.        ,
             25.        ,      0.        ,      0.        ],
        [     1.54499996,      1.54499996,      1.54499996,
              1.54499996,  16760.        ,      0.        ],
        [    23.89999962,     24.5       ,     22.20000076,
             22.20000076, 199628.        ,      0.        ],
        [    36.79999924,     

In [94]:
stock_matrix

array([[[    25.        ,     25.        ,     25.        ,
             25.        ,      0.        ,      0.        ],
        [     1.472     ,      1.472     ,      1.39999998,
              1.39999998,  22480.        ,      0.        ],
        [    23.35000038,     23.35000038,     21.14999962,
             21.14999962, 124154.        ,      0.        ],
        [    34.65000153,     36.45000076,     30.20000076,
             30.5       ,  16288.        ,      0.        ],
        [    19.39999962,     21.14999962,     19.20000076,
             20.79999924, 381921.        ,      0.        ]],

       [[    25.        ,     25.        ,     25.        ,
             25.        ,      0.        ,      0.        ],
        [     1.54499996,      1.54499996,      1.54499996,
              1.54499996,  16760.        ,      0.        ],
        [    23.89999962,     24.5       ,     22.20000076,
             22.20000076, 199628.        ,      0.        ],
        [    36.79999924,     

In [95]:
stock_matrix.shape

(2712, 5, 6)

In [96]:
np.save("stock_price_matrix.npy",stock_matrix)

In [97]:
#构建新的股票矩阵
stock_matrix_adjust = stock_matrix[:,:,:-1]

In [98]:
stock_matrix_adjust

array([[[    25.        ,     25.        ,     25.        ,
             25.        ,      0.        ],
        [     1.472     ,      1.472     ,      1.39999998,
              1.39999998,  22480.        ],
        [    23.35000038,     23.35000038,     21.14999962,
             21.14999962, 124154.        ],
        [    34.65000153,     36.45000076,     30.20000076,
             30.5       ,  16288.        ],
        [    19.39999962,     21.14999962,     19.20000076,
             20.79999924, 381921.        ]],

       [[    25.        ,     25.        ,     25.        ,
             25.        ,      0.        ],
        [     1.54499996,      1.54499996,      1.54499996,
              1.54499996,  16760.        ],
        [    23.89999962,     24.5       ,     22.20000076,
             22.20000076, 199628.        ],
        [    36.79999924,     38.59999847,     33.        ,
             35.04999924,  22900.        ],
        [    19.39999962,     20.        ,     19.10000038,
  

In [101]:
stock_matrix_adjust[np.isnan(stock_matrix_adjust)] = 0
np.save("stock_price_matrix_adjust.npy",stock_matrix_adjust)