In [1]:
import numpy as np
import pandas as pd
np.set_printoptions(suppress=True)

In [39]:
data = pd.read_excel(r"C:\Users\Sivakumar\Desktop\GCN_stock_price_prediction-main\tech_sorted.xlsx",index_col=0)
data

4THGEN.BO  4THGEN.BO.1  4THGEN.BO.2  4THGEN.BO.3  4THGEN.BO.4  \
DATE                                                                        
2010-01-04       25.0         25.0         25.0         25.0          0.0   
2010-01-05       25.0         25.0         25.0         25.0          0.0   
2010-01-06       25.0         25.0         25.0         25.0          0.0   
2010-01-07       25.0         25.0         25.0         25.0          0.0   
2010-01-08       25.0         25.0         25.0         25.0          0.0   
...               ...          ...          ...          ...          ...   
2020-12-23        4.0          4.0          4.0          4.0          0.0   
2020-12-24        4.0          4.0          4.0          4.0          0.0   
2020-12-28        4.0          4.0          4.0          4.0          0.0   
2020-12-29        4.0          4.0          4.0          4.0          0.0   
2020-12-30        4.0          4.0          4.0          4.0          0.0   

            ACIIN.BO  ACIIN.BO.1  ACIIN.BO.2  ACIIN.BO.3  ACIIN.BO.4  ...  \
DATE                                                                  ...   
2010-01-04     1.472       1.472       1.400       1.400     22480.0  ...   
2010-01-05     1.545       1.545       1.545       1.545     16760.0  ...   
2010-01-06     1.622       1.622       1.545       1.545     38510.0  ...   
2010-01-07     1.703       1.703       1.703       1.703     38390.0  ...   
2010-01-08     1.767       1.788       1.618       1.788     80490.0  ...   
...              ...         ...         ...         ...         ...  ...   
2020-12-23     0.400       0.400       0.400       0.400       354.0  ...   
2020-12-24     0.410       0.410       0.410       0.410      2150.0  ...   
2020-12-28     0.400       0.400       0.400       0.400      3101.0  ...   
2020-12-29     0.420       0.420       0.420       0.420      1100.0  ...   
2020-12-30     0.420       0.420       0.420       0.420         0.0  ...   

              AJEL.BO  AJEL.BO.1  AJEL.BO.2  AJEL.BO.3  AJEL.BO.4  \
DATE                                                                
2010-01-04  34.650002  36.450001  30.200001  30.500000      16288   
2010-01-05  36.799999  38.599998  33.000000  35.049999      22900   
2010-01-06  41.450001  42.900002  34.049999  37.500000      27946   
2010-01-07  40.099998  43.000000  39.099998  43.000000      12725   
2010-01-08  41.099998  45.000000  39.299999  45.000000      18240   
...               ...        ...        ...        ...        ...   
2020-12-23   2.450000   2.450000   2.450000   2.450000       1220   
2020-12-24   2.450000   2.450000   2.450000   2.450000          0   
2020-12-28   2.690000   2.690000   2.650000   2.650000       1969   
2020-12-29   2.820000   2.820000   2.820000   2.820000        211   
2020-12-30   2.960000   2.960000   2.960000   2.960000        632   

            AKSHOPTFBR.BO  AKSHOPTFBR.BO.1  AKSHOPTFBR.BO.2  AKSHOPTFBR.BO.3  \
DATE                                                                           
2010-01-04      19.400000        21.150000        19.200001        20.799999   
2010-01-05      19.400000        20.000000        19.100000        19.799999   
2010-01-06      20.049999        20.200001        19.549999        19.799999   
2010-01-07      20.250000        20.549999        19.750000        19.750000   
2010-01-08      21.600000        21.850000        20.100000        21.000000   
...                   ...              ...              ...              ...   
2020-12-23       7.350000         7.390000         6.800000         7.250000   
2020-12-24       7.810000         8.080000         7.300000         8.000000   
2020-12-28       7.800000         7.940000         7.540000         7.920000   
2020-12-29       7.820000         8.000000         7.300000         7.300000   
2020-12-30       7.730000         7.900000         7.350000         7.900000   

            AKSHOPTFBR.BO.4  
DATE                         
2010-01-0

In [40]:
#close, high, low, open, volume
stock_price_data = np.load(r"C:\Users\Sivakumar\Desktop\GCN_stock_price_prediction-main\Sample_Dataset_code\stock_price_matrix_adjust.npy")
stock_price_data

array([[[    25.        ,     25.        ,     25.        ,
             25.        ,      0.        ],
        [     1.472     ,      1.472     ,      1.39999998,
              1.39999998,  22480.        ],
        [    23.35000038,     23.35000038,     21.14999962,
             21.14999962, 124154.        ],
        [    34.65000153,     36.45000076,     30.20000076,
             30.5       ,  16288.        ],
        [    19.39999962,     21.14999962,     19.20000076,
             20.79999924, 381921.        ]],

       [[    25.        ,     25.        ,     25.        ,
             25.        ,      0.        ],
        [     1.54499996,      1.54499996,      1.54499996,
              1.54499996,  16760.        ],
        [    23.89999962,     24.5       ,     22.20000076,
             22.20000076, 199628.        ],
        [    36.79999924,     38.59999847,     33.        ,
             35.04999924,  22900.        ],
        [    19.39999962,     20.        ,     19.10000038,
  

In [41]:
stock_price_data.shape

(2712, 5, 5)

In [42]:
ad_sample_data = stock_price_data
ad_sample_data[np.isnan(ad_sample_data)] = 5

In [43]:
ad_sample_data

array([[[    25.        ,     25.        ,     25.        ,
             25.        ,      0.        ],
        [     1.472     ,      1.472     ,      1.39999998,
              1.39999998,  22480.        ],
        [    23.35000038,     23.35000038,     21.14999962,
             21.14999962, 124154.        ],
        [    34.65000153,     36.45000076,     30.20000076,
             30.5       ,  16288.        ],
        [    19.39999962,     21.14999962,     19.20000076,
             20.79999924, 381921.        ]],

       [[    25.        ,     25.        ,     25.        ,
             25.        ,      0.        ],
        [     1.54499996,      1.54499996,      1.54499996,
              1.54499996,  16760.        ],
        [    23.89999962,     24.5       ,     22.20000076,
             22.20000076, 199628.        ],
        [    36.79999924,     38.59999847,     33.        ,
             35.04999924,  22900.        ],
        [    19.39999962,     20.        ,     19.10000038,
  

In [44]:
Pearson_stock_price = np.zeros((ad_sample_data.shape[1],ad_sample_data.shape[1]))
Pearson_stock_price.shape

(5, 5)

In [45]:
#(N,N) - Pearson
for i in range(ad_sample_data.shape[1]):
    x = ad_sample_data[:,i,0]
    for j in range(ad_sample_data.shape[1]):
        y = ad_sample_data[:,j,0]
        pccs = np.corrcoef(x, y)
        Pearson_stock_price[i,j] = pccs[0,1]
Pearson_stock_price

array([[ 1.        ,  0.04987455,  0.67080818,  0.57231438, -0.27551475],
       [ 0.04987455,  1.        ,  0.04671114, -0.20652669,  0.18554448],
       [ 0.67080818,  0.04671114,  1.        ,  0.81072034,  0.12920231],
       [ 0.57231438, -0.20652669,  0.81072034,  1.        ,  0.10635695],
       [-0.27551475,  0.18554448,  0.12920231,  0.10635695,  1.        ]])

In [46]:
Pearson_stock_price[np.isnan(Pearson_stock_price)] = 0

In [47]:
Pearson_stock_price

array([[ 1.        ,  0.04987455,  0.67080818,  0.57231438, -0.27551475],
       [ 0.04987455,  1.        ,  0.04671114, -0.20652669,  0.18554448],
       [ 0.67080818,  0.04671114,  1.        ,  0.81072034,  0.12920231],
       [ 0.57231438, -0.20652669,  0.81072034,  1.        ,  0.10635695],
       [-0.27551475,  0.18554448,  0.12920231,  0.10635695,  1.        ]])

In [48]:
np.save("Pearson_stock_price.npy",Pearson_stock_price)