In [100]:
import numpy as np
import pandas as pd

In [119]:
data=pd.read_excel(r"C:\Users\Sivakumar\Desktop\GCN_stock_price_prediction-main\technology_shareholding_sorted.xlsx")
data

NAME  PROMOTER  PUBLIC  DII   FII
0      4THGEN.BO     36.17   63.83    0  0.00
1       ACIIN.BO     22.88   77.12    0  0.00
2   AISHWARYA.BO     29.61   70.39    0  0.00
3        AJEL.BO     49.45   50.55    0  0.00
4  AKSHOPTFBR.BO     27.95   71.80    0  0.25
5  AKSHOPTFBR.NS     27.95   71.80    0  0.25

In [120]:
'''print(data.iloc[0][0])
print(data.iloc[1][0])
print(data.iloc[2])
print(data.iloc[3])'''

l1 = []
for i in range(5):
    for j in range(1,5):
        l1.append(data.iloc[i][j])
#print(l1)
arr_1 = np.reshape(l1, (5,4))
print(arr_1)


[[36.17 63.83  0.    0.  ]
 [22.88 77.12  0.    0.  ]
 [29.61 70.39  0.    0.  ]
 [49.45 50.55  0.    0.  ]
 [27.95 71.8   0.    0.25]]


In [121]:
adj_mat = np.zeros((5,5))
#print(adj_mat)
#print(arr_1[0])
#s0s1 s0s2 s0s3 s1s2 s1s3 s2s3
sqsumarr= []
for i in range(5):
    sqsum = 0
    for j in range(i+1, 5):
        for k in range(4):
            sqsum = sqsum + (arr_1[j][k] - arr_1[i][k])**2
            #print(j, k,  "minus", i, k)
        sqsum = (sqsum)**(0.5)
        adj_mat[i][j] = adj_mat[j][i] =  sqsum

#print(sqsumarr)
print(adj_mat)

[[ 0.         18.79489824 10.24021964 19.05143091 12.25574277]
 [18.79489824  0.          9.51765727 37.70208823  9.57976452]
 [10.24021964  9.51765727  0.         28.05799708  5.73273033]
 [19.05143091 37.70208823 28.05799708  0.         30.23036553]
 [12.25574277  9.57976452  5.73273033 30.23036553  0.        ]]


In [122]:
adj_mat[np.isnan(adj_mat)] = 0
np.save("shareholding_relation_adjacent_matrix_tongyi.npy",adj_mat)